// Định nghĩa các roles trong hệ thống
export const ROLES = {
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  DATA_ENTRY: 'DATA_ENTRY',
  PHARMACIST: 'PHARMACIST',
  RECEPTIONIST: 'RECEPTIONIST',
};

// Định nghĩa các permissions
export const PERMISSIONS = {
  // Quản lý bệnh nhân
  PATIENT_VIEW: 'PATIENT_VIEW',
  PATIENT_CREATE: 'PATIENT_CREATE',
  PATIENT_EDIT: 'PATIENT_EDIT',
  PATIENT_DELETE: 'PATIENT_DELETE',
  
  // Quản lý hồ sơ y tế
  MEDICAL_RECORD_VIEW: 'MEDICAL_RECORD_VIEW',
  MEDICAL_RECORD_CREATE: 'MEDICAL_RECORD_CREATE',
  MEDICAL_RECORD_EDIT: 'MEDICAL_RECORD_EDIT',
  
  // Phân tích và báo cáo
  ANALYSIS_VIEW: 'ANALYSIS_VIEW',
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',
  
  // Quản trị hệ thống
  ADMIN_PANEL: 'ADMIN_PANEL',
  USER_MANAGE: 'USER_MANAGE',
  SYSTEM_CONFIG: 'SYSTEM_CONFIG',
  
  // Chăm sóc bệnh nhân
  CARE_PLAN_VIEW: 'CARE_PLAN_VIEW',
  CARE_PLAN_CREATE: 'CARE_PLAN_CREATE',
  CARE_PLAN_EDIT: 'CARE_PLAN_EDIT',
};

// Mapping roles với permissions
export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_EDIT,
    PERMISSIONS.PATIENT_DELETE,
    PERMISSIONS.MEDICAL_RECORD_VIEW,
    PERMISSIONS.MEDICAL_RECORD_CREATE,
    PERMISSIONS.MEDICAL_RECORD_EDIT,
    PERMISSIONS.ANALYSIS_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.ADMIN_PANEL,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.SYSTEM_CONFIG,
    PERMISSIONS.CARE_PLAN_VIEW,
    PERMISSIONS.CARE_PLAN_CREATE,
    PERMISSIONS.CARE_PLAN_EDIT,
  ],
  [ROLES.DOCTOR]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_EDIT,
    PERMISSIONS.MEDICAL_RECORD_VIEW,
    PERMISSIONS.MEDICAL_RECORD_CREATE,
    PERMISSIONS.MEDICAL_RECORD_EDIT,
    PERMISSIONS.ANALYSIS_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.CARE_PLAN_VIEW,
    PERMISSIONS.CARE_PLAN_CREATE,
    PERMISSIONS.CARE_PLAN_EDIT,
  ],
  [ROLES.NURSE]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_EDIT,
    PERMISSIONS.MEDICAL_RECORD_VIEW,
    PERMISSIONS.MEDICAL_RECORD_CREATE,
    PERMISSIONS.CARE_PLAN_VIEW,
    PERMISSIONS.CARE_PLAN_EDIT,
  ],
  [ROLES.DATA_ENTRY]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_EDIT,
    PERMISSIONS.MEDICAL_RECORD_VIEW,
    PERMISSIONS.MEDICAL_RECORD_CREATE,
  ],
  [ROLES.PHARMACIST]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.MEDICAL_RECORD_VIEW,
  ],
  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_EDIT,
  ],
};

// Helper function để check permission
export const hasPermission = (userRole, permission) => {
  const permissions = ROLE_PERMISSIONS[userRole] || [];
  return permissions.includes(permission);
};

// Helper function để check role
export const hasRole = (userRole, allowedRoles) => {
  return allowedRoles.includes(userRole);
};
